<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsAanvullendeMedicatiebewakingsgegevensQuery;

class GsAanvullendeMedicatiebewakingsgegevensQuery extends BaseGsAanvullendeMedicatiebewakingsgegevensQuery
{
}
