<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsAanvullendeMedicatiebewakingsgegevensPeer;

class GsAanvullendeMedicatiebewakingsgegevensPeer extends BaseGsAanvullendeMedicatiebewakingsgegevensPeer
{
}
