<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsBewakingenTeControlerenIndicatiesQuery;

class GsBewakingenTeControlerenIndicatiesQuery extends BaseGsBewakingenTeControlerenIndicatiesQuery
{
}
