<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsCoderingGedifferentieerdeTarievenQuery;

class GsCoderingGedifferentieerdeTarievenQuery extends BaseGsCoderingGedifferentieerdeTarievenQuery
{
}
