<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsDeclaratietabelDureGeneesmiddelenQuery;

class GsDeclaratietabelDureGeneesmiddelenQuery extends BaseGsDeclaratietabelDureGeneesmiddelenQuery
{
}
