<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsInteractiesOmschrijvingCoderingWfgPeer;

class GsInteractiesOmschrijvingCoderingWfgPeer extends BaseGsInteractiesOmschrijvingCoderingWfgPeer
{
}
