<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsIndicatiesBijSupplementaireProductenPeer;

class GsIndicatiesBijSupplementaireProductenPeer extends BaseGsIndicatiesBijSupplementaireProductenPeer
{
}
