<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsRelatiesTussenThesaurusitemnummersPeer;

class GsRelatiesTussenThesaurusitemnummersPeer extends BaseGsRelatiesTussenThesaurusitemnummersPeer
{
}
