<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsRelatiesTussenThesaurusitemnummersQuery;

class GsRelatiesTussenThesaurusitemnummersQuery extends BaseGsRelatiesTussenThesaurusitemnummersQuery
{
}
