<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsSupplementaireProductenMetNzaMaximumtariefQuery;

class GsSupplementaireProductenMetNzaMaximumtariefQuery extends BaseGsSupplementaireProductenMetNzaMaximumtariefQuery
{
}
