<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsSupplementaireProductenMetNzaMaximumtarief;

class GsSupplementaireProductenMetNzaMaximumtarief extends BaseGsSupplementaireProductenMetNzaMaximumtarief
{
}
