<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsSupplementaireProductenMetNzaMaximumtariefPeer;

class GsSupplementaireProductenMetNzaMaximumtariefPeer extends BaseGsSupplementaireProductenMetNzaMaximumtariefPeer
{
}
