<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsVoorschrijfprIdentificerendeVeldenQuery;

class GsVoorschrijfprIdentificerendeVeldenQuery extends BaseGsVoorschrijfprIdentificerendeVeldenQuery
{
}
