<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsVoorschrijfprIdentificerendeVeldenPeer;

class GsVoorschrijfprIdentificerendeVeldenPeer extends BaseGsVoorschrijfprIdentificerendeVeldenPeer
{
}
