<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsVoorschrijfprGeneesmiddelIdentificQuery;

class GsVoorschrijfprGeneesmiddelIdentificQuery extends BaseGsVoorschrijfprGeneesmiddelIdentificQuery
{
}
