<?php

namespace PharmaIntelligence\GstandaardBundle\Model;

use PharmaIntelligence\GstandaardBundle\Model\om\BaseGsVoorschrijfprGeneesmiddelIdentificPeer;

class GsVoorschrijfprGeneesmiddelIdentificPeer extends BaseGsVoorschrijfprGeneesmiddelIdentificPeer
{
}
